{{- if .Values.externalSecret.enabled }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  backendType: {{ .Values.externalSecret.backendType }}
{{- if eq .Values.externalSecret.backendType "vault" }}
  vaultMountPoint: {{ .Values.externalSecret.vaultMountPoint }}
  vaultRole: {{ .Values.externalSecret.vaultRole }}
{{- end }}
{{- if .Values.externalSecret.data }}
  data:
  {{- toYaml .Values.externalSecret.data | nindent 4 }}
{{- end }}
{{- if .Values.externalSecret.dataFrom }}
  dataFrom:
  {{- range .Values.externalSecret.dataFrom }}
    - {{ . }}
  {{- end }}
{{- end }}
{{- end }}