apiVersion: v2
name: service
description: A Helm chart for Kubernetes
type: application
version: 1.18.7
home: https://github.com/registfyrepos/helm-chart
sources:
- https://github.com/registfyrepos/helm-chart